ZSH_CONFIG_DIR="$XDG_CONFIG_HOME/zsh"

ZSH_TMUX_DEFAULT_SESSION_NAME="master"
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_UNICODE=true
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt interactivecomments

# Variables
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
unset KUBECONFIG

# Needed to use bins installed via go install
export PATH=$PATH:$(go env GOPATH)/bin/

# On WSL opencode gives segmentation fault without setting this up
export PATH=$PATH:$HOME/.opencode/bin

# Add this to path for installs from binary
export PATH=$PATH:$HOME/.local/bin

for f in $XDG_CONFIG_HOME/zsh/*.zsh; do
  source "$f"
done

eval "$(starship init zsh)"
eval "$(zoxide init --cmd cd zsh)"
