ZSH_CONFIG_DIR="$XDG_CONFIG_HOME/zsh"

ZSH_TMUX_DEFAULT_SESSION_NAME="master"
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_UNICODE=true
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt interactivecomments

# Variables
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
unset KUBECONFIG

# Source plugins first as it might override other commands
[ -f $XDG_CONFIG_HOME/zsh/plugins.zsh ] && source $XDG_CONFIG_HOME/zsh/plugins.zsh

for f in $XDG_CONFIG_HOME/zsh/*.zsh; do
  [[ "$f" == *"plugins.zsh" ]] && continue
  source "$f"
done


eval "$(starship init zsh)"
eval "$(zoxide init --cmd cd zsh)"
