ZSH_CONFIG_DIR="$HOME/.config/zsh"

ZSH_TMUX_DEFAULT_SESSION_NAME="master"
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_UNICODE=true
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt interactivecomments

# Variables
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH" # Export mason installed bins
export PATH="$PATH:/opt/nvim-linux64/bin"
export PATH=$PATH:$(go env GOPATH)/bin/
export XDG_CONFIG_HOME="$HOME/.config" # dotfiles on ~/.config
export STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/starship.toml


# Source plugins first as it might override other commands
[ -f ~/.config/zsh/plugins.zsh ] && source ~/.config/zsh/plugins.zsh

for f in ~/.config/zsh/*.zsh; do
  [[ "$f" == *"plugins.zsh" ]] && continue
  source "$f"
done


eval "$(starship init zsh)"
eval "$(zoxide init --cmd cd zsh)"
export PATH="$HOME/.local/bin:$PATH"
